## async / await



async / await는 프로미스를 기반으로 동적한다. async / await를 사용하면 프로미스의 후속 처리 메서드에 콜백 함수를 전달해서 비동기 처리 결과를

후속 처리할 필요 없이 마치 동기 처리처럼 프로미스를 사용할 수 있다.

```javascript
async function fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';
  
  const res = await fetch(url);
  const todo = await res.json();
  console.log(todo);
  // {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
}

fetchTodo();
```



### 1. async 함수

await 키워드는 반드시 async 함수 내부에서 사용해야 한다. async 함수는 언제나 프로미스를 반환한다. 명시적으로 프로미스를 반환하지 않아도

암묵적으로 반환값을 resolve하는 프로미스를 반환한다.

```javascript
async function foo(n) { return n; }
foo(1).then(console.log); // 1

const bar = async function (n) { return n ;}
bar(2).then(console.log); // 2

const baz = async n => n;
baz(3).then(console.log); // 3

const obj = {
  async foo(n) { return n; }
}
obj.foo(4).then(console.log); // 4

class MyClass {
  async bar(n) { return n; }
}
const myClass = new MyClass();
myClass.bar(5).then(console.log); // 5
```



### 2. await 키워드

await 키워드는 프로미스가 settled 상태가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환한다.

반드시 프로미스 앞에서 사용해야 한다.

```javascript
const getGithubUserName = async id => {
  const res = await fetch(`https://api.github.com/users/${id}`)
  const { name } = await res.json();
  
  console.log(name);
};

getGithubUserName('ungmo2')
```

await 키워드는 프로미스가 settled 상태가 되면 프로미스가 resolve한 처리 결과가 res 변수에 할당된다.

```javascript
async function foo() {
  const a = await new Promise(resolve => setTimeout(() => resolve(1), 3000));
  const b = await new Promise(resolve => setTimeout(() => resolve(2), 2000));
  const c = await new Promise(resolve => setTimeout(() => resolve(3), 1000));
  
  console.log([a, b, c]);
}

foo(); 
```

위와 같은 처리는 총 6초가 소요된다. 그런데 3개의 비동기 처리는 서로 연관이 없기 때문에 Promise.all 메서드를 사용하는 것이 좋다.

```javascript
async function foo() {
  const res = await Promise.all([
    new Promise(resolve => setTimeout(() => resolve(1), 3000)),
    new Promise(resolve => setTimeout(() => resolve(2), 2000)),
    new Promise(resolve => setTimeout(() => resolve(3), 1000))
  ]);
  
  console.log(res);
};

foo();
```



### 3. 에러 처리

async / await 에서 에러 처리는 try ...catch 문을 사용할 수 있다. 

```javascript
const foo = async () => {
  try {
    const wrongUrl = 'http://wrong.url';
    
    const response = await fetch(wrongUrl);
    const data = await response.json();
    console.log(data)
  } catch (e) {
    console.error(err); // TypeError: Failed to fetch
  }
};

foo();
```

async 함수 내에서 catch 문을 사용해서 에러 처리를 하지 않으면 async 함수는 발생한 에러를 reject 하는 프로미스를 반환한다.

